# Generated by Django 3.2 on 2022-03-05 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0003_rename_meals_meal'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='category',
            field=models.CharField(default='pasta', max_length=50),
            preserve_default=False,
        ),
    ]
