# Generated by Django 3.2 on 2022-03-06 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0004_meal_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='calories',
            field=models.IntegerField(default=500),
        ),
        migrations.AlterField(
            model_name='meal',
            name='category',
            field=models.CharField(choices=[('starter', 'starter'), ('pizza', 'pizza'), ('speciality', 'speciality'), ('pasta', 'pasta'), ('salad', 'salad'), ('dessert', 'dessert'), ('drink', 'drink')], default='starter', max_length=50),
        ),
    ]
