# Generated by Django 3.2 on 2022-03-07 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0006_category'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='Menus',
        ),
    ]
