# Generated by Django 3.2 on 2022-03-07 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0007_rename_category_menus'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Menus',
            new_name='Menu',
        ),
    ]
