# Generated by Django 3.2 on 2022-03-07 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0008_rename_menus_menu'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='menu',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='meals.menu'),
        ),
    ]
