# Generated by Django 3.2 on 2022-03-07 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0009_meal_menu'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Menu',
            new_name='Category',
        ),
        migrations.RemoveField(
            model_name='meal',
            name='menu',
        ),
    ]
