# Generated by Django 3.2 on 2022-03-07 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0012_alter_meal_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='category',
            field=models.CharField(choices=[('starter', 'starter'), ('pizza', 'pizza'), ('speciality', 'speciality'), ('pasta', 'pasta'), ('salad', 'salad'), ('dessert', 'dessert'), ('drink', 'drink')], default='starter', max_length=50, null=True),
        ),
    ]
