# Generated by Django 3.2 on 2022-03-07 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0013_alter_meal_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meal',
            name='category',
        ),
    ]
