# Generated by Django 3.2 on 2022-03-07 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0014_remove_meal_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
