# Generated by Django 3.2 on 2022-03-07 20:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0015_delete_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='meal',
            name='category',
            field=models.CharField(choices=[('starter', 'starter'), ('pizza', 'pizza'), ('speciality', 'speciality'), ('pasta', 'pasta'), ('salad', 'salad'), ('dessert', 'dessert'), ('drink', 'drink')], default='starter', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='meal',
            name='category1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='meals.category'),
        ),
    ]
