# Generated by Django 3.2 on 2022-03-07 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0016_auto_20220307_2047'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meal',
            name='category1',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
