# Generated by Django 3.2 on 2022-03-07 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0017_auto_20220307_2107'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='category1',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
