# Generated by Django 3.2 on 2022-03-07 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0018_meal_category1'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='meal',
            name='category1',
        ),
    ]
