# Generated by Django 3.2 on 2022-03-08 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0020_alter_meal_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='dinner',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='meal',
            name='lunch',
            field=models.BooleanField(default=False),
        ),
    ]
