# Generated by Django 3.2 on 2022-03-08 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0022_alter_meal_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='alergens',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
