# Generated by Django 3.2 on 2022-03-08 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0023_alter_meal_alergens'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='alergens',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
