# Generated by Django 3.2 on 2022-03-09 21:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0024_alter_meal_alergens'),
    ]

    operations = [
        migrations.CreateModel(
            name='Allergen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='meal',
            name='alergens',
        ),
        migrations.AlterField(
            model_name='meal',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category', related_query_name='category', to='meals.category'),
        ),
        migrations.AddField(
            model_name='meal',
            name='allergens',
            field=models.ManyToManyField(to='meals.Allergen'),
        ),
    ]
