# Generated by Django 3.2 on 2022-03-09 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0025_auto_20220309_2105'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meal',
            name='allergens',
        ),
    ]
