# Generated by Django 3.2 on 2022-03-19 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0033_remove_drink_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drink',
            name='description',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
