# Generated by Django 3.2 on 2022-03-19 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0034_alter_drink_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drink',
            name='description',
            field=models.CharField(max_length=100),
        ),
    ]
