# Generated by Django 3.2 on 2022-03-28 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_alter_contact_phone'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': 'Message', 'verbose_name_plural': 'Messages'},
        ),
    ]
