# Generated by Django 3.2 on 2022-03-21 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carousel',
            old_name='name',
            new_name='title',
        ),
        migrations.AddField(
            model_name='carousel',
            name='body',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
    ]
