# Generated by Django 3.2 on 2022-03-21 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20220321_1134'),
    ]

    operations = [
        migrations.AddField(
            model_name='carousel',
            name='name',
            field=models.CharField(default='Carousel 1', max_length=30),
            preserve_default=False,
        ),
    ]
