# Generated by Django 3.2 on 2022-03-13 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about',
            options={'verbose_name': 'Chef', 'verbose_name_plural': 'Chefs'},
        ),
    ]
