# Generated by Django 3.2 on 2022-03-13 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_alter_about_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about',
            options={'verbose_name': 'About', 'verbose_name_plural': 'About'},
        ),
    ]
