# Generated by Django 3.2 on 2022-03-13 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0004_alter_about_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chef',
            options={'verbose_name': 'Chef', 'verbose_name_plural': 'Chefs'},
        ),
        migrations.AlterModelOptions(
            name='reason',
            options={'verbose_name': 'Reason', 'verbose_name_plural': 'Reasons'},
        ),
    ]
