# Generated by Django 3.2 on 2022-03-13 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0005_auto_20220313_1234'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reason',
            name='image',
        ),
    ]
