# Generated by Django 3.2 on 2022-03-19 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0006_remove_reason_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='body',
            field=models.TextField(max_length=1000),
        ),
    ]
