# Generated by Django 3.2 on 2022-03-28 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0009_alter_comment_body'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['created_on'], 'verbose_name': 'Comment', 'verbose_name_plural': 'Comments'},
        ),
    ]
