# Generated by Django 3.2 on 2022-03-12 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BookingModel',
            new_name='Booking',
        ),
    ]
